# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae8e12206fd0b5617000eff413c5425f3e40a09870f5f627f889cb11ca43d07d5160eea8409fd7fce7eb72477bc9afec5332616c56f589934527919c9ff70fe2

test:
  secret_key_base: 92aa8dfcd43f18812ab26e28c0bf393a828984254ae536f5a69b744a5bdfd8b8c607c10950cb0843a7dd28c450c17d657f4025268637a1e646e38148fc80949c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
